force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobNeighbor__c/ClusterJobNeighbor__c.object-meta.xml
<CustomObject>
    <label>Cluster Job Neighbor</label>
    <nameField>
        <displayFormat>CJN-{0000}</displayFormat>
        <label>Cluster Job Neighbor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Job Neighbors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobNeighbor__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipLabel>Cluster Job Nearest Neighbors</relationshipLabel>
    <relationshipName>ClusterJobNeighbors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ClusterJobNeighbor__c/fields/ClusterJobResult__c.field-meta.xml
<CustomField>
    <fullName>ClusterJobResult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cluster Job Result</label>
    <referenceTo>ClusterJobResult__c</referenceTo>
    <relationshipLabel>Cluster Job Nearest Neighbors</relationshipLabel>
    <relationshipName>Cluster_Job_Neighbors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJobNeighbor__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJobNeighbor__c/fields/NeighborRecordId__c.field-meta.xml
<CustomField>
    <fullName>NeighborRecordId__c</fullName>
    <label>Neighbor Record Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobNeighbor__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/ClusterJobResult__c.object-meta.xml
<CustomObject>
    <label>Cluster Job Result</label>
    <nameField>
        <displayFormat>CJR-{0000}</displayFormat>
        <label>ClusterJobResult Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Job Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipLabel>Cluster Job Results</relationshipLabel>
    <relationshipName>ClusterJobResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClusterDataPointNeighbor.cls
/*
 * Represents a record neighbor - wrapper for ClusterJobNeighbor__c
 *
 * @author: Iskander Mukhamedgaliyev
 */
global with sharing class ClusterDataPointNeighbor implements Comparable {
    @AuraEnabled
    public String externalRecordId;
    @AuraEnabled
    public Double distance;
    @AuraEnabled
    public Id recordId;
    @AuraEnabled
    public Id jobId;
    @AuraEnabled
    public String neighborExternalRecordId;
    @AuraEnabled
    public ClusterDataPoint neighborDataPoint;

    public ClusterDataPointNeighbor() {

    }

    public ClusterDataPointNeighbor(ClusterJobNeighbor__c jobNeighbor) {
        this.recordId = jobNeighbor.Id;
        this.distance = Double.valueOf(jobNeighbor.Distance__c);
        this.externalRecordId = jobNeighbor.RecordId__c;
        this.jobId = jobNeighbor.ClusterJob__c;
        this.neighborExternalRecordId = jobNeighbor.NeighborRecordId__c;
    }

    public void populateNeighborRecord(ClusterJobNeighbor__c jobNeighbor) {
        jobNeighbor.Distance__c = Decimal.valueOf(this.distance);
        jobNeighbor.RecordId__c = this.externalRecordId;
        jobNeighbor.ClusterJob__c = this.jobId;
        jobNeighbor.NeighborRecordId__c = this.neighborExternalRecordId;
        jobNeighbor.ClusterJobResult__c = this.neighborDataPoint.recordId;
    }

    /**
     * Allow to sort neighbors
     */
    public Integer compareTo(Object compareTo) {
        ClusterDataPointNeighbor other = (ClusterDataPointNeighbor) compareTo;
        return ClusterDataHelper.compareDoubles(this.distance, other.distance);
    }

    global String getExternalRecordId() {
        return this.externalRecordId;
    }

    global Double getDistance() {
        return this.distance;
    }

    global Id getRecordId() {
        return this.recordId;
    }

    global Id getJobId() {
        return this.jobId;
    }

    global String getNeighborExternalRecordId() {
        return this.neighborExternalRecordId;
    }

    global ClusterDataPoint getNeighborDataPoint() {
        return this.neighborDataPoint;
    }

}