force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJob__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>JobStatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>MarkedForCancel</fullName>
                <label>Marked for Cancel</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatusText__c.field-meta.xml
<CustomField>
    <fullName>JobStatusText__c</fullName>
    <label>Job Status Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <label>Number Of Clusters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Contains Silhouette score of all clusters in the job. Value ranges from −1 to +1, a high value indicates that the objects are well matched to their clusters</description>
    <label>Silhouette Score</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/ClusterJobCluster__c.object-meta.xml
<CustomObject>
    <label>Job Result Cluster</label>
    <nameField>
        <displayFormat>CJC-{0000}</displayFormat>
        <label>ClusterJobCluster Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Result Clusters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipName>JobClusters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterName__c.field-meta.xml
<CustomField>
    <fullName>ClusterName__c</fullName>
    <label>Cluster Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterNumber__c.field-meta.xml
<CustomField>
    <fullName>ClusterNumber__c</fullName>
    <label>Cluster Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClusterJobDetailsUiModel.cls
/*
 * UI model for job details lightning component
 *
 * @author: Iskander Mukhamedgaliyev
 */
public with sharing class ClusterJobDetailsUiModel {
    public class ClusterJobCluster {
        @AuraEnabled
        public Id clusterId;
        @AuraEnabled
        public String clusterNumber;
        @AuraEnabled
        public String clusterName;
        @AuraEnabled
        public Integer recordCount;
    }
    public ClusterJobDetailsUiModel() {

    }

    public ClusterJobDetailsUiModel(ClusterJob__c clusterJob) {
        this.jobId = clusterJob.Id;
        this.name = clusterJob.Name;
        this.objectName = clusterJob.ObjectName__c;
        this.status = clusterJob.JobStatus__c;
        this.startDate = clusterJob.StartDate__c == null ? '' : clusterJob.StartDate__c.format();
        this.endDate = clusterJob.EndDate__c == null ? '' : clusterJob.EndDate__c.format();
        this.clusters = new List<ClusterJobCluster>();
        this.statusText = clusterJob.JobStatusText__c;        
        this.numberOfClusters = Integer.valueOf(clusterJob.NumberOfClusters__c);
        this.createdById = clusterJob.CreatedById;
        this.createdByName = clusterJob.CreatedBy.Name + ', ' + clusterJob.CreatedDate.format();
        this.jobName = clusterJob.JobName__c;
        this.score = clusterJob.Score__c;
        for (ClusterJobCluster__c jobCluster:clusterJob.JobClusters__r) {
            ClusterJobCluster clusterWrapper = new ClusterJobCluster();
            clusterWrapper.clusterId = jobCluster.Id;
            clusterWrapper.clusterName = jobCluster.ClusterName__c;
            if (clusterWrapper.clusterName == null) clusterWrapper.clusterName = 'Cluster ' + jobCluster.ClusterNumber__c;
            clusterWrapper.clusterNumber = jobCluster.ClusterNumber__c;
            this.clusters.add(clusterWrapper);
        }
    }

    @AuraEnabled
    public Id jobId;
    @AuraEnabled
    public Id createdById;
    @AuraEnabled
    public String createdByName;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String jobName;
    @AuraEnabled
    public String objectName;
    @AuraEnabled
    public String status;
    @AuraEnabled
    public String statusText;
    @AuraEnabled
    public String jobStateString;
    @AuraEnabled
    public String startDate;
    @AuraEnabled
    public String endDate;
    @AuraEnabled
    public Integer numberOfClusters;
    @AuraEnabled
    public ClusterModelWrapper model;
    @AuraEnabled
    public Integer numberOfRecords;
    @AuraEnabled
    public Double score;
    @AuraEnabled
    public Integer maxGraphDataPoints;
    @AuraEnabled
    public List<ClusterJobCluster> clusters;
    @AuraEnabled
    public String[] clusterColors;
}