force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobResult__c/ClusterJobResult__c.object-meta.xml
<CustomObject>
    <label>Cluster Job Result</label>
    <nameField>
        <displayFormat>CJR-{0000}</displayFormat>
        <label>ClusterJobResult Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Job Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobResult__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>ClusterJobCluster__c</referenceTo>
    <relationshipLabel>Cluster Job Results</relationshipLabel>
    <relationshipName>ClusterJobResults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipLabel>Cluster Job Results</relationshipLabel>
    <relationshipName>ClusterJobResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterNumber__c.field-meta.xml
<CustomField>
    <fullName>ClusterNumber__c</fullName>
    <label>Cluster Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/Json__c.field-meta.xml
<CustomField>
    <fullName>Json__c</fullName>
    <label>Json</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <label>Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/algorithms/classes/ClusterKMeansCentroidUpdateStep.cls
/*
 * K-means centroid update step - calculates new mean values for centroids
 *
 * @author: Iskander Mukhamedgaliyev
 */
public with sharing class ClusterKMeansCentroidUpdateStep extends ClusterBatchBase implements ClusterAlgorithmStep {

    Integer[] clusterSizes;

    public ClusterKMeansCentroidUpdateStep () {
    }

    public override void init(ClusterAlgorithmRunner runner) {
        ClusterBatchBase.log.debug('Starting KMeans centroid update step');
        super.init(runner);
        ClusterKMeansJobState jobState = (ClusterKMeansJobState)runner.getJobState();
        ClusterModelWrapper model = jobState.model;
        jobState.hasAssignmentChanged = false;
        List<ClusterDataPoint> centroids = jobState.centroids;
        this.clusterSizes = new Integer[centroids.size()];
        for (Integer cindex=0; cindex<centroids.size(); cindex++) {
            for (Integer i=0; i<model.fields.size(); i++) {
                if (model.fields[i].distanceType == ClusterConstants.FIELDTYPE_NUMERIC) {
                    centroids[cindex].values[i] = 0; //initialize with zero
                }
                else if (model.fields[i].isNameField) {
                    centroids[cindex].recordName = 'Centroid ' + String.valueOf(cindex); //Update name to not point to real data point anymore since it will represent mean
                    centroids[cindex].values[i] = centroids[cindex].recordName;
                }
                else if (model.fields[i].isIdField) {
                    centroids[cindex].recordId = null; 
                    centroids[cindex].values[i] = String.valueOf(cindex); //Update real id to cluster index, same as above
                }
            }
            this.clusterSizes[cindex] = 0;
        }
    }
    
    protected override Database.QueryLocator getBatchQueryLocator() {
        ClusterKMeansJobState jobState = (ClusterKMeansJobState)runner.getJobState();
        return Database.getQueryLocator([SELECT Id, Cluster__c, Json__c, RecordId__c, RecordName__c, ClusterNumber__c, ClusterJob__c FROM ClusterJobResult__c WHERE ClusterJob__c = :jobState.clusterJob.Id]);
    }

    public override void processRecords(Database.BatchableContext bc, List<SObject> scope) {        
        ClusterKMeansJobState jobState = (ClusterKMeansJobState)this.runner.getJobState();
        ClusterModelWrapper model = jobState.model;
        ClusterMinMaxValue[] minMaxValues = jobState.minMaxValues;
        Integer length = model.fields.size();
        Integer scopeSize = scope.size();
        List<ClusterDataPoint> centroids = jobState.centroids;
        for (Integer sindex = 0; sindex < scopeSize; sindex++){
            ClusterJobResult__c currentRecord = (ClusterJobResult__c)scope[sindex];
            ClusterDataPoint currentDataPoint = new ClusterDataPoint(currentRecord);
            ClusterDataPoint currentCentroid = centroids[currentDataPoint.clusterIndex];
            //Calculating per cluster sum and count of all data point values
            for (Integer findex=0; findex<model.fields.size(); findex++) {
                if (model.fields[findex].distanceType == ClusterConstants.FIELDTYPE_NUMERIC) {
                    currentCentroid.values[findex] = Double.valueOf(currentCentroid.values[findex]) + Double.valueOf(currentDataPoint.values[findex]);
                }
            }
            this.clusterSizes[currentDataPoint.clusterIndex]++;
        }
    }

    public override void done(){
        ClusterKMeansJobState jobState = (ClusterKMeansJobState)runner.getJobState();
        ClusterModelWrapper model = jobState.model;
        List<ClusterDataPoint> centroids = jobState.centroids;
        //Calculating centroid mean values
        for (Integer cindex=0; cindex<centroids.size(); cindex++) {
            if (this.clusterSizes[cindex] != 0) {
                for (Integer i=0; i<model.fields.size(); i++) {
                    if (model.fields[i].distanceType == ClusterConstants.FIELDTYPE_NUMERIC) {
                        centroids[cindex].values[i] = Double.valueOf(centroids[cindex].values[i])/this.clusterSizes[cindex];
                    }
                }
            }
            centroids[cindex].clusterIndex = cindex;
        }
        this.clusterSizes = null;
        super.done();
    }
}