force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobCluster__c/ClusterJobCluster__c.object-meta.xml
<CustomObject>
    <label>Job Result Cluster</label>
    <nameField>
        <displayFormat>CJC-{0000}</displayFormat>
        <label>ClusterJobCluster Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Result Clusters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipName>JobClusters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ClusterJobState.cls
/*
 * Holds state of the current algorithm
 *
 * @author: Iskander Mukhamedgaliyev
 */
public virtual class ClusterJobState {
    public ClusterJobState() {

    }
    public ClusterModelWrapper model;
    public ClusterMinMaxValue[] minMaxValues;
    public Id currentJobId;
    public ClusterJob__c clusterJob;
    public ClusterJobCluster__c[] jobClusters;
    public Integer currentAlgorithmStep;
    public Integer totalIterationsCount;
    public Integer numRecords;
}