force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJob__c/fields/ClusterModel__c.field-meta.xml
<CustomField>
    <fullName>ClusterModel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model</label>
    <referenceTo>ClusterModel__c</referenceTo>
    <relationshipLabel>Cluster Jobs</relationshipLabel>
    <relationshipName>Cluster_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/InternalJobId__c.field-meta.xml
<CustomField>
    <fullName>InternalJobId__c</fullName>
    <label>Internal Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>JobStatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>MarkedForCancel</fullName>
                <label>Marked for Cancel</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatusText__c.field-meta.xml
<CustomField>
    <fullName>JobStatusText__c</fullName>
    <label>Job Status Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <label>Number Of Clusters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Contains Silhouette score of all clusters in the job. Value ranges from −1 to +1, a high value indicates that the objects are well matched to their clusters</description>
    <label>Silhouette Score</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/ClusterModel__c.object-meta.xml
<CustomObject>
    <label>Cluster Model</label>
    <nameField>
        <label>ClusterModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModel__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Default Number Of Clusters</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/algorithms/classes/ClusterAlgorithmFactory.cls
/*
 * Algorithm factory - creates algorithm runners
 *
 * @author: Iskander Mukhamedgaliyev
 */
public with sharing class ClusterAlgorithmFactory {
    public static List<UiSelectOption> getAlgorithmList() {
        //TODO: move this to some settings class, possibly create custom setings
        List<UiSelectOption> values = new List<UiSelectOption>();
        values.add(new UiSelectOption(ClusterConstants.ALGORITHM_KMEDOIDS, ClusterConstants.ALGORITHM_KMEDOIDS ));
        values.add(new UiSelectOption(ClusterConstants.ALGORITHM_KMEANS, ClusterConstants.ALGORITHM_KMEANS ));
        return values;
    }

    public static ClusterAlgorithmRunner getRunner(ClusterModelWrapper model) {
        return getRunner(model.algorithm);
    }

    public static ClusterAlgorithmRunner getRunner(String algorithm) {
        if (algorithm == ClusterConstants.ALGORITHM_KMEDOIDS) {
            return new ClusterKMedoidsPAMRunner();
        }
        else if (algorithm == ClusterConstants.ALGORITHM_KMEANS) {
            return new ClusterKMeansRunner();
        }
        else {
            throw new ClusterException(algorithm + ' algorithm is not supported');
        }
    }

    public static ClusterAlgorithmRunner getRunnerFromJobId(Id jobId) {
        List<ClusterJob__c> jobRecords = [SELECT Id, JobName__c, ClusterModel__c, ClusterModel__r.Algorithm__c, NumberOfClusters__c, ObjectName__c, JobStatus__c, JobStatusText__c, StartDate__c, EndDate__c, InternalJobId__c, Score__c 
            FROM ClusterJob__c WHERE Id = :jobId WITH SECURITY_ENFORCED];
        if (jobRecords.size() != 1) {
            throw new ClusterException('Cannot find cluster job with id ' + jobId);
        }
        ClusterJob__c job = jobRecords.get(0);        
        ClusterAlgorithmRunner runner = ClusterAlgorithmFactory.getRunner(job.ClusterModel__r.Algorithm__c);
        String jobStateJson = ClusterJobManager.loadJobState(jobId);
        runner.setJobState(jobStateJson);
        return runner;
    }
}