force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJob__c/fields/ClusterModel__c.field-meta.xml
<CustomField>
    <fullName>ClusterModel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model</label>
    <referenceTo>ClusterModel__c</referenceTo>
    <relationshipLabel>Cluster Jobs</relationshipLabel>
    <relationshipName>Cluster_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>JobStatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>MarkedForCancel</fullName>
                <label>Marked for Cancel</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <label>Number Of Clusters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/ClusterModel__c.object-meta.xml
<CustomObject>
    <label>Cluster Model</label>
    <nameField>
        <label>ClusterModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModel__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/isCustomSoql__c.field-meta.xml
<CustomField>
    <fullName>isCustomSoql__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Custom Soql</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Default Number Of Clusters</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ClusterPredictController.cls
public with sharing class ClusterPredictController {
    @AuraEnabled    
    public static ClusterPredictUiModel getPredictUiModel(Id recordId) {
        String keyCode  = String.valueOf(recordId).subString(0,3);
        String objectName = null;
        Schema.DescribeSObjectResult objectDescribe = null;
        ClusterPredictUiModel uiModel = new ClusterPredictUiModel();

        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        for (Schema.SObjectType objectInstance : gd.values())
        {
            objectDescribe = objectInstance.getDescribe();
            if(objectDescribe.getKeyPrefix() == keyCode)
            {
                objectName = objectDescribe.getName();                
                break;
            }
        }
        if (objectName != null) {
            ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterModel__c);
            ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterJob__c);
            uiModel.models = new List<ClusterModelWrapper>();
            if (objectDescribe.getSObjectType() == ClusterModel__c.getSObjectType()) {
                ClusterModelWrapper model = ClusterModelBuilderController.loadModel(recordId);
                uiModel.models.add(model);
                uiModel.jobState = getModelJobState(model.modelId);
                if (uiModel.jobState == null) {
                    throw new ClusterException('This model doesn\'t have any completed jobs. Run this model first to use predict functionality');
                }
                uiModel.recordIdNeeded = true;
            }
            else if (objectDescribe.getSObjectType() == ClusterJob__c.getSObjectType()) {
                List<ClusterJob__c> jobs = [SELECT Id,ClusterModel__c FROM ClusterJob__c WHERE Id = :recordId AND JobStatus__c = :ClusterConstants.JOBSTATUS_COMPLETED  
                    WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC LIMIT 1];
                if (jobs.size() == 1) {
                    uiModel.jobState = ClusterJobManager.loadJobState(jobs[0].Id);
                }
                else {
                    throw new ClusterException('This job is not completed. Predict can only be used on completed jobs');
                }
                uiModel.recordIdNeeded = true;
            }
            else {
                List<ClusterModel__c> modelList = [SELECT Id, Name, Object__c, Algorithm__c, Filter__c, Parameters__c, SOQL__c , isCustomSoql__c, Description__c, NumberOfClusters__c 
                    FROM ClusterModel__c WHERE Object__c = :objectName WITH SECURITY_ENFORCED ORDER BY Object__c, Name];                
                
                for (ClusterModel__c model:modelList) {
                    ClusterModelWrapper modelWrapper = new ClusterModelWrapper(model);
                    uiModel.models.add(modelWrapper);
                }
                if (modelList.size() == 1) {
                    Id modelId = modelList[0].Id;
                    uiModel.jobState = getModelJobState(modelId);
                }
                uiModel.recordIdNeeded = false;
            }
        }
        return uiModel;
    }

    @AuraEnabled
    public static string getModelJobState(Id modelId){
        ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterJob__c);
        String jobState = null;
        List<ClusterJob__c> jobs = [SELECT Id FROM ClusterJob__c WHERE JobStatus__c = :ClusterConstants.JOBSTATUS_COMPLETED AND ClusterModel__c = :modelId 
            WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC LIMIT 1];
        if (jobs.size() == 1) {
            jobState = ClusterJobManager.loadJobState(jobs[0].Id);
        }
        return jobState;
    }
}