force-app/main/default/objects/ClusterJob__c/ClusterJob__c.object-meta.xml
<CustomObject>
    <label>Cluster Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>ClusterJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJob__c/fields/ClusterModel__c.field-meta.xml
<CustomField>
    <fullName>ClusterModel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model</label>
    <referenceTo>ClusterModel__c</referenceTo>
    <relationshipLabel>Cluster Jobs</relationshipLabel>
    <relationshipName>Cluster_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>JobStatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>MarkedForCancel</fullName>
                <label>Marked for Cancel</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/JobStatusText__c.field-meta.xml
<CustomField>
    <fullName>JobStatusText__c</fullName>
    <label>Job Status Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <label>Number Of Clusters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Contains Silhouette score of all clusters in the job. Value ranges from −1 to +1, a high value indicates that the objects are well matched to their clusters</description>
    <label>Silhouette Score</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJob__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/ClusterJobCluster__c.object-meta.xml
<CustomObject>
    <label>Job Result Cluster</label>
    <nameField>
        <displayFormat>CJC-{0000}</displayFormat>
        <label>ClusterJobCluster Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Result Clusters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipName>JobClusters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterName__c.field-meta.xml
<CustomField>
    <fullName>ClusterName__c</fullName>
    <label>Cluster Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobCluster__c/fields/ClusterNumber__c.field-meta.xml
<CustomField>
    <fullName>ClusterNumber__c</fullName>
    <label>Cluster Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/ClusterJobResult__c.object-meta.xml
<CustomObject>
    <label>Cluster Job Result</label>
    <nameField>
        <displayFormat>CJR-{0000}</displayFormat>
        <label>ClusterJobResult Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Job Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterJobResult__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>ClusterJobCluster__c</referenceTo>
    <relationshipLabel>Cluster Job Results</relationshipLabel>
    <relationshipName>ClusterJobResults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterJob__c.field-meta.xml
<CustomField>
    <fullName>ClusterJob__c</fullName>
    <label>Cluster Job</label>
    <referenceTo>ClusterJob__c</referenceTo>
    <relationshipLabel>Cluster Job Results</relationshipLabel>
    <relationshipName>ClusterJobResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterName__c.field-meta.xml
<CustomField>
    <fullName>ClusterName__c</fullName>
    <formula>HYPERLINK( Cluster__r.Id, Cluster__r.ClusterName__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cluster Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/ClusterNumber__c.field-meta.xml
<CustomField>
    <fullName>ClusterNumber__c</fullName>
    <label>Cluster Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/Json__c.field-meta.xml
<CustomField>
    <fullName>Json__c</fullName>
    <label>Json</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/Random__c.field-meta.xml
<CustomField>
    <fullName>Random__c</fullName>
    <label>Random</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterJobResult__c/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <label>Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/ClusterModel__c.object-meta.xml
<CustomObject>
    <label>Cluster Model</label>
    <nameField>
        <label>ClusterModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModel__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Default Number Of Clusters</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClusterJobDetailsController.cls
/*
 * Controller for job details lightning component
 *
 * @author: Iskander Mukhamedgaliyev
 */
public with sharing class ClusterJobDetailsController {

    @AuraEnabled
    public static ClusterJobDetailsUiModel getJob(Id jobId) {
        ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterJob__c);
        //isAccessible permission is checked in ClusterAccessCheck.checkReadPermission above, exception is thrown in case of no access
        ClusterJob__c job = [SELECT Id, Name, JobName__c, ClusterModel__c, JobStatus__c,JobStatusText__c,ObjectName__c,StartDate__c,EndDate__c,NumberOfClusters__c,
                CreatedById, CreatedBy.Name, Score__c, CreatedDate,
                (SELECT Id, ClusterName__c, ClusterNumber__c FROM JobClusters__r ORDER BY ClusterNumber__c)
                FROM ClusterJob__c WHERE Id = :jobId];
        ClusterJobDetailsUiModel jobModel = new ClusterJobDetailsUiModel(job);
        jobModel.jobStateString = ClusterJobManager.loadJobState(jobId);
        jobModel.model = ClusterModelBuilderController.loadModel(job.ClusterModel__c);
        if (jobModel.status == ClusterConstants.JOBSTATUS_COMPLETED) {
            jobModel.numberOfRecords = 0;
            //isAccessible permission is checked in ClusterAccessCheck.checkReadPermission above, exception is thrown in case of no access
            List<AggregateResult> arList = [SELECT Cluster__c clusterId, count(Id) recordCount FROM ClusterJobResult__c WHERE ClusterJob__c=:jobId GROUP BY Cluster__c];
            Map<String, ClusterJobDetailsUiModel.ClusterJobCluster> clusters = new Map<String, ClusterJobDetailsUiModel.ClusterJobCluster>();
            for (ClusterJobDetailsUiModel.ClusterJobCluster cluster:jobModel.clusters) {
                clusters.put(String.valueOf(cluster.clusterId), cluster);
            }
            for (AggregateResult ar:arList) {
                ClusterJobDetailsUiModel.ClusterJobCluster cluster = clusters.get(String.valueOf(ar.get('clusterId')));
                if (cluster != null) {
                    cluster.recordCount = Integer.valueOf(ar.get('recordCount'));
                    jobModel.numberOfRecords += cluster.recordCount;
                }
            }
        }
        jobModel.maxGraphDataPoints = ClusterConstants.getTSNEPlotLimit();
        return jobModel;
    }

    public static ClusterDataPoint[] getDataPoints(Id jobId, Integer maxCount, Integer offset) {
        Integer count = ClusterConstants.getTSNEPlotLimit();
        if (offset > count) {
            return new List<ClusterDataPoint>();
        }
        if (offset + maxCount > count) {
            count = count - offset;
        }
        else {
            count = maxCount;
        }
        ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterJobResult__c);
        //isAccessible permission is checked in ClusterAccessCheck.checkReadPermission above, exception is thrown in case of no access
        List<ClusterJobResult__c> randomRecords = [SELECT Id, Cluster__c, Json__c, RecordId__c, RecordName__c, ClusterNumber__c, ClusterJob__c 
            FROM ClusterJobResult__c WHERE ClusterJob__c = :jobId WITH SECURITY_ENFORCED ORDER BY Random__c LIMIT :count OFFSET :offset];
        List<ClusterDataPoint> dataPoints = new List<ClusterDataPoint>();
        for (ClusterJobResult__c record:randomRecords) {
            ClusterDataPoint dp = new ClusterDataPoint(record, null);
            //We will parse json in javascript to save apex CPU time
            dp.valuesJson = record.Json__c;
            dataPoints.add(dp);
        }
        return dataPoints; 
    }

    @AuraEnabled
    public static String getDataPointsJson(Id jobId, Integer maxCount, Integer offset) {
        //We will load data points in batches to avoid heap size issues
        List<ClusterDataPoint> dataPoints = getDataPoints(jobId, maxCount, offset);
        //There is a weird bug with @AuraEnabled and Object[] json deserialization - it skips null items
        //So we will serialize manually here and deserialize in javascript controller until that is fixed
        //This is bad and consumes apex memory, but fixes the problem for now
        return JSON.serialize(dataPoints); 
    }

    @AuraEnabled
    public static ClusterJobDetailsUiModel cancelJob(Id jobId) {
        ClusterAccessCheck.checkCRUDPermission(Schema.SObjectType.ClusterJob__c);
        //CRUD permissions are checked in ClusterAccessCheck.checkCRUDPermission above, exception is thrown in case of no access
        ClusterJob__c job = [SELECT Id, Name, JobName__c, ClusterModel__c, JobStatus__c,JobStatusText__c,ObjectName__c,StartDate__c,EndDate__c,NumberOfClusters__c,
                CreatedById, CreatedBy.Name, Score__c FROM ClusterJob__c WHERE Id = :jobId];
        if (job.JobStatus__c == ClusterConstants.JOBSTATUS_NEW || job.JobStatus__c == ClusterConstants.JOBSTATUS_IN_PROGRESS) {
            job.JobStatus__c = ClusterConstants.JOBSTATUS_MARKED_FOR_CANCEL;
            job.JobStatusText__c = 'User requested to cancel this job';
            update job;
        }
        return getJob(jobId);
    }

    @AuraEnabled
    public static ClusterJobDetailsUiModel setJobName(Id jobId, String jobName) {
        ClusterAccessCheck.checkCRUDPermission(Schema.SObjectType.ClusterJob__c);
        //CRUD permissions are checked in ClusterAccessCheck.checkCRUDPermission above, exception is thrown in case of no access
        ClusterJob__c job = [SELECT Id, Name, JobName__c, ClusterModel__c, JobStatus__c,JobStatusText__c,ObjectName__c,StartDate__c,EndDate__c,NumberOfClusters__c,
                CreatedById, CreatedBy.Name, Score__c FROM ClusterJob__c WHERE Id = :jobId];
        job.JobName__c = jobName;
        update job;
        return getJob(jobId);     
    }

    @AuraEnabled
    public static ClusterResultDetailsUiModel getJobResultModel(Id jobResultId){
        ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterJobResult__c);
        List<ClusterJobResult__c> results = [SELECT Id, Name, Cluster__c, Cluster__r.ClusterName__c, Json__c, RecordId__c, RecordName__c, ClusterNumber__c, ClusterJob__c 
            FROM ClusterJobResult__c WHERE Id = :jobResultId WITH SECURITY_ENFORCED];
        
        ClusterJobResult__c result = results.get(0);
        ClusterJob__c job = ClusterJobManager.getJob(result.ClusterJob__c);
        
        ClusterJobState jobState = new ClusterJobState();
        jobState.model = ClusterModelBuilderController.loadModel(job.ClusterModel__c);

        ClusterSObjectProcessor objectProcessor = new ClusterSObjectProcessor(jobState);
        ClusterDataPoint dp = new ClusterDataPoint(result, objectProcessor);

        ClusterResultDetailsUiModel uiModel = new ClusterResultDetailsUiModel();
        uiModel.jobId = job.Id;
        uiModel.jobName = job.JobName__c;
        uiModel.jobStateString = ClusterJobManager.loadJobState(job.Id);
        uiModel.dataPoint = dp;
        uiModel.resultName = result.Name;
        uiModel.clusterId = result.Cluster__c;
        if (result.Cluster__r != null) {
            uiModel.clusterName = result.Cluster__r.ClusterName__c;
        }
        return uiModel; 
    }
}