force-app/main/default/objects/ClusterModelField__c/ClusterModelField__c.object-meta.xml
<CustomObject>
    <label>Cluster Model Field</label>
    <nameField>
        <displayFormat>CMF-{0000}</displayFormat>
        <label>Cluster Model Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Model Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModelField__c/fields/DistanceType__c.field-meta.xml
<CustomField>
    <fullName>DistanceType__c</fullName>
    <label>Distance Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Numeric</fullName>
            </value>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>LongText</fullName>
                <label>Long Text</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Output</fullName>
                <label>Cluster Result Output</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/fields/RelationName__c.field-meta.xml
<CustomField>
    <fullName>RelationName__c</fullName>
    <label>Relation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Weight</label>
    <precision>12</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClusterModelFieldWrapper.cls
/*
 * This is a wrapper class for ClusterModelField__c
 *
 * @author: Iskander Mukhamedgaliyev
 */
public class ClusterModelFieldWrapper {
    public ClusterModelFieldWrapper() {

    }
    public ClusterModelFieldWrapper(ClusterModelField__c field) {
        this.fieldId = field.Id;
        this.name = field.FieldName__c;
        this.distanceType = field.DistanceType__c;
        this.objectName = field.ObjectName__c;
        this.relationName = field.RelationName__c; 
        this.weight = field.Weight__c;
        this.language = field.Language__c;
    }
    public void populateFieldRecord(ClusterModelField__c field){
        field.Id = this.fieldId;
        field.FieldName__c = this.name;
        field.DistanceType__c = this.distanceType;
        field.ObjectName__c = this.objectName;
        field.RelationName__c = this.relationName; 
        field.Weight__c = this.weight;
        field.Language__c = this.language;
    }

    public virtual void loadFromMap(Map<String, Object> fieldValues) {
        this.fieldId = Id.valueOf((String)fieldValues.get('fieldId'));
        this.name = (String)fieldValues.get('name');
        this.displayLabel = (String)fieldValues.get('displayLabel');
        this.distanceType = (String)fieldValues.get('distanceType');
        this.objectName = (String)fieldValues.get('objectName');
        this.relationName = (String)fieldValues.get('relationName');
        this.weight = (Decimal)fieldValues.get('weight');
        this.dataType = (String)fieldValues.get('dataType');
        this.language = (String)fieldValues.get('language');
    }

    @AuraEnabled
    public Id fieldId;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String displayLabel;
    @AuraEnabled
    public String distanceType;
    @AuraEnabled
    public String objectName;
    @AuraEnabled
    public String relationName;
    @AuraEnabled
    public Decimal weight;
    @AuraEnabled
    public String dataType;
    @AuraEnabled
    public String language;
    @AuraEnabled
    public Boolean isNumeric;
    @AuraEnabled
    public Boolean isText;
    @AuraEnabled
    public Boolean isLongText;
    @AuraEnabled
    public Boolean isCategory;
    public Boolean isIdField;
    public Boolean isNameField;
}