force-app/main/default/objects/ClusterModel__c/ClusterModel__c.object-meta.xml
<CustomObject>
    <label>Cluster Model</label>
    <nameField>
        <label>ClusterModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModel__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/isCustomSoql__c.field-meta.xml
<CustomField>
    <fullName>isCustomSoql__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Custom Soql</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Default Number Of Clusters</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ClusterModelLauncherController.cls
public with sharing class ClusterModelLauncherController {
    public static Logger log = LogFactory.getLogger();

    @AuraEnabled
    public static ClusterModelLauncherUiModel loadModel(Id modelId) {
        ClusterModelLauncherUiModel uiModel = new ClusterModelLauncherUiModel();
        uiModel.model = ClusterModelBuilderController.loadModel(modelId);
        ClusterAlgorithmRunner runner = ClusterAlgorithmFactory.getRunner(uiModel.model);
        uiModel.parameters = runner.getParameters(uiModel.model);
        return uiModel;
    }

    @AuraEnabled
    public static string runModel(Id modelId, Map<String, Object> parameters){
        //TODO: consider runModel as a global api method in future versions
        ClusterModelWrapper model = ClusterModelBuilderController.loadModel(modelId);
        log.debug('Starting cluster model ' + model.name + ' with parameters ' + parameters);
        ClusterAlgorithmRunner runner = ClusterAlgorithmFactory.getRunner(model);
        model.parameters = parameters;
        //We will validate model and permissions one time here
        ClusterAlgorithmRunner.ModelValidationResult vr = runner.validateModel(model);
        if (!vr.isValid) {
            ClusterException ex = new ClusterException();
            ex.setMessage('Model validation failed. Error message(s): ' + String.join(vr.messages,'\n'));
            log.error(ex.getMessage(), ex);
            throw ex;
        }
        runner.init(model);
        runner.start();
        ClusterJobState state = runner.getJobState();
        return state.clusterJob.Id;
    }

    @AuraEnabled
    public static ClusterJobRunnerUiModel getModels(){
        ClusterAccessCheck.checkReadPermission(Schema.SObjectType.ClusterModel__c);
        List<ClusterModel__c> modelList = [SELECT Id, Name, Object__c, Algorithm__c, Filter__c, Parameters__c, SOQL__c , isCustomSoql__c, Description__c, NumberOfClusters__c 
            FROM ClusterModel__c WITH SECURITY_ENFORCED ORDER BY Object__c, Name];
        ClusterJobRunnerUiModel uiModel = new ClusterJobRunnerUiModel();
        uiModel.models = new List<ClusterModelWrapper>();
        for (ClusterModel__c model:modelList) {
            ClusterModelWrapper modelWrapper = new ClusterModelWrapper(model);
            uiModel.models.add(modelWrapper);
        }
        uiModel.parameters = new Map<String, List<ClusterAlgorithmParameter>>();
        for (UiSelectOption algorithm : ClusterAlgorithmFactory.getAlgorithmList()) {
            uiModel.parameters.put(algorithm.value, ClusterAlgorithmFactory.getRunner(algorithm.value).getParameters(null));
        }
        return uiModel;
    }
}