force-app/main/default/objects/ClusterModel__c/ClusterModel__c.object-meta.xml
<CustomObject>
    <label>Cluster Model</label>
    <nameField>
        <label>ClusterModel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModel__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/isCustomSoql__c.field-meta.xml
<CustomField>
    <fullName>isCustomSoql__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Custom Soql</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/NumberOfClusters__c.field-meta.xml
<CustomField>
    <fullName>NumberOfClusters__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Default Number Of Clusters</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModel__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClusterModelField__c/ClusterModelField__c.object-meta.xml
<CustomObject>
    <label>Cluster Model Field</label>
    <nameField>
        <displayFormat>CMF-{0000}</displayFormat>
        <label>Cluster Model Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Model Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClusterModelField__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>ClusterModel</label>
    <referenceTo>ClusterModel__c</referenceTo>
    <relationshipLabel>Cluster Model Fields</relationshipLabel>
    <relationshipName>ClusterModelFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ClusterModelWrapper.cls
/*
 * Represents a cluster model, wrapper for ClusterModel__c
 * Used almost everywhere in UI and calculations
 *
 * @author: Iskander Mukhamedgaliyev
 */
public class ClusterModelWrapper {
    public ClusterModelWrapper() {
        this.parameters = new Map<String, Object>();
    }
    public ClusterModelWrapper(ClusterModel__c model) {
        this.modelId = model.Id;
        this.name = model.Name;
        this.description = model.Description__c;
        this.algorithm = model.Algorithm__c;
        this.filter = model.Filter__c;
        if (model.Parameters__c != null && model.Parameters__c != '') {
            this.parameters = (Map<String, Object>)JSON.deserializeUntyped(model.Parameters__c);
        }
        this.soql = model.SOQL__c;
        this.objectName = model.Object__c;
        this.isCustomSoql = model.isCustomSoql__c;
        this.numberOfClusters = model.NumberOfClusters__c == null ? 0 : model.NumberOfClusters__c.intValue();
        this.populateModelFields(model.ClusterModelFields__r);
    }
    public void populateModelRecord(ClusterModel__c model){
        model.Id = this.modelId;
        model.Name = this.name;
        model.Description__c = this.description;
        model.Algorithm__c = this.algorithm;
        model.Filter__c = this.filter;
        model.Parameters__c = JSON.serialize(this.parameters);
        model.SOQL__c = this.soql;
        model.Object__c = this.objectName;
        model.isCustomSoql__c = this.isCustomSoql;
        model.NumberOfClusters__c = this.numberOfClusters;
    }
    public void populateModelFields(List<ClusterModelField__c> modelFields){
        this.fields = new List<ClusterModelFieldWrapper>();
        if (modelFields == null || modelFields.size() == 0) return;
        Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{objectName});
        System.assertNotEquals(descResult.size(), 0, 'Cannot find object ' + objectName + ' in the describe result');
        Map<String,Schema.SObjectField> fieldsMap = descResult[0].fields.getMap();
        for (ClusterModelField__c cmf:modelFields) {
            ClusterModelFieldWrapper field = new ClusterModelFieldWrapper(cmf);
            SObjectField sof = fieldsMap.get(field.name);
            DescribeFieldResult fd = sof == null ? null : sof.getDescribe();
            this.populateField(field, fd);
            this.fields.add(field);
        }
    }
    public void prepare() {
        Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{objectName});
        System.assertNotEquals(descResult.size(), 0, 'Cannot find object ' + objectName + ' in the describe result');
        Map<String,Schema.SObjectField> fieldsMap = descResult[0].fields.getMap();
        for (ClusterModelFieldWrapper field:this.fields) {
            SObjectField sof = fieldsMap.get(field.name);
            DescribeFieldResult fd = sof == null ? null : sof.getDescribe();
            this.populateField(field, fd);
        }
    }
    private void populateField(ClusterModelFieldWrapper field, DescribeFieldResult fd) {
        if (fd != null) {
            field.isIdField = field.name.toLowerCase() == 'id';
            field.isNameField = fd.isNameField();
            field.dataType = fd.getType().name().toLowerCase();
        }
        field.isNumeric = field.distanceType == ClusterConstants.FIELDTYPE_NUMERIC;
        field.isText = field.distanceType == ClusterConstants.FIELDTYPE_TEXT;
        field.isLongText = field.distanceType == ClusterConstants.FIELDTYPE_LONGTEXT;
        field.isCategory = field.distanceType == ClusterConstants.FIELDTYPE_CATEGORY;
    }
    public List<ClusterModelField__c> getModelFields() {
        List<ClusterModelField__c> modelFields = new List<ClusterModelField__c>();
        for (ClusterModelFieldWrapper fieldWrapper:this.fields) {
            ClusterModelField__c field = new ClusterModelField__c();
            fieldWrapper.populateFieldRecord(field);
            field.Id = null;
            if (Schema.sObjectType.ClusterModelField__c.fields.Model__c.isAccessible() && Schema.sObjectType.ClusterModelField__c.fields.Model__c.isCreateable()) {
                field.Model__c = this.modelId;
            }
            modelFields.add(field);
        }
        return modelFields;
    }
    public Boolean hasLongTextFields() {
        Boolean hasLongText = false;
        for (ClusterModelFieldWrapper field : this.fields) {
            if (field.isLongText) {
                hasLongText = true;
                break;
            }
        }
        return hasLongText;
    }

    @AuraEnabled
    public Id modelId;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String description;
    @AuraEnabled
    public String algorithm;
    @AuraEnabled
    public String filter;
    @AuraEnabled
    public String objectName;
    @AuraEnabled
    public Map<String, Object> parameters;
    @AuraEnabled
    public Integer numberOfClusters;
    @AuraEnabled
    public String soql;
    @AuraEnabled
    public Boolean isCustomSoql;
    @AuraEnabled
    public String distanceFunction;
    @AuraEnabled
    public List<ClusterModelFieldWrapper> fields;
}